# Generated by Django 4.2.7 on 2023-12-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.FileField(blank=True, null=True, upload_to='dp'),
        ),
    ]
