# Generated by Django 4.2.7 on 2023-12-24 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_alter_profile_bio_alter_profile_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='contents'),
        ),
        migrations.CreateModel(
            name='Vids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
