# Generated by Django 4.2.7 on 2023-12-24 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_art_image_vids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vids',
            name='user',
        ),
        migrations.AddField(
            model_name='art',
            name='prof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
        ),
        migrations.AddField(
            model_name='vids',
            name='prof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
