# Generated by Django 4.2 on 2024-01-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_like_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likex',
            field=models.IntegerField(default=0),
        ),
    ]
