# Generated by Django 4.2 on 2024-01-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile_likex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='art',
        ),
        migrations.AddField(
            model_name='like',
            name='art',
            field=models.ManyToManyField(to='base.art'),
        ),
    ]
