# Generated by Django 4.2 on 2024-01-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_like_art_like_art'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='count',
        ),
    ]
