# Generated by Django 4.2 on 2024-01-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_like_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
                ('reason', models.TextField()),
            ],
        ),
    ]
